-- claude-mem v12.3.9 synthetic fixture schema
-- Generated by docs/research/2026-04-24-v0.6-verifications helper script
-- (migrations 001 + 002 applied verbatim from installed plugin source)
-- PRAGMA user_version = 2

CREATE TABLE diagnostics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT,
  message TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'info',
  created_at TEXT NOT NULL,
  created_at_epoch INTEGER NOT NULL,
  project TEXT NOT NULL,
  origin TEXT NOT NULL DEFAULT 'system',
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE SET NULL
);

CREATE TABLE memories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  text TEXT NOT NULL,
  document_id TEXT UNIQUE,
  keywords TEXT,
  created_at TEXT NOT NULL,
  created_at_epoch INTEGER NOT NULL,
  project TEXT NOT NULL,
  archive_basename TEXT,
  origin TEXT NOT NULL DEFAULT 'transcript', title TEXT, subtitle TEXT, facts TEXT, concepts TEXT, files_touched TEXT,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE overviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL,
  created_at_epoch INTEGER NOT NULL,
  project TEXT NOT NULL,
  origin TEXT NOT NULL DEFAULT 'claude',
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT UNIQUE NOT NULL,
  project TEXT NOT NULL,
  created_at TEXT NOT NULL,
  created_at_epoch INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'compress',
  archive_path TEXT,
  archive_bytes INTEGER,
  archive_checksum TEXT,
  archived_at TEXT,
  metadata_json TEXT
);

CREATE TABLE transcript_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  project TEXT,
  event_index INTEGER NOT NULL,
  event_type TEXT,
  raw_json TEXT NOT NULL,
  captured_at TEXT NOT NULL,
  captured_at_epoch INTEGER NOT NULL,
  FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
  UNIQUE(session_id, event_index)
);

CREATE INDEX idx_diagnostics_created ON diagnostics(created_at_epoch DESC);

CREATE INDEX idx_diagnostics_project ON diagnostics(project);

CREATE INDEX idx_diagnostics_session ON diagnostics(session_id);

CREATE INDEX idx_diagnostics_severity ON diagnostics(severity);

CREATE INDEX idx_memories_concepts ON memories(concepts);

CREATE INDEX idx_memories_created_at ON memories(created_at_epoch DESC);

CREATE INDEX idx_memories_document_id ON memories(document_id);

CREATE INDEX idx_memories_origin ON memories(origin);

CREATE INDEX idx_memories_project ON memories(project);

CREATE INDEX idx_memories_project_created ON memories(project, created_at_epoch DESC);

CREATE INDEX idx_memories_session ON memories(session_id);

CREATE INDEX idx_memories_title ON memories(title);

CREATE INDEX idx_overviews_created_at ON overviews(created_at_epoch DESC);

CREATE INDEX idx_overviews_project ON overviews(project);

CREATE INDEX idx_overviews_project_created ON overviews(project, created_at_epoch DESC);

CREATE UNIQUE INDEX idx_overviews_project_latest ON overviews(project, created_at_epoch DESC);

CREATE INDEX idx_overviews_session ON overviews(session_id);

CREATE INDEX idx_sessions_created_at ON sessions(created_at_epoch DESC);

CREATE INDEX idx_sessions_project ON sessions(project);

CREATE INDEX idx_sessions_project_created ON sessions(project, created_at_epoch DESC);

CREATE INDEX idx_transcript_events_captured ON transcript_events(captured_at_epoch DESC);

CREATE INDEX idx_transcript_events_project ON transcript_events(project);

CREATE INDEX idx_transcript_events_session ON transcript_events(session_id, event_index);

CREATE INDEX idx_transcript_events_type ON transcript_events(event_type);
